### ISSUE TITLE
Plugin not working after Sentinel Hub upgrade

### ISSUE THREAD

**Issue by gmilcinski** [sinergise/qgis_sentinel_hub#3]
I have just noticed, that the plugin on github still points to our old version of services. 
This means that the layers/configurations created after November 23rd are not working.

A workakound should be pretty easy, you just need to change fifth line in Settings.py from:
urlBase = 'http://services.sentinel-hub.com/v1/‘
to
urlBase = 'http://services.sentinel-hub.com/ogc/'

**Comment by AleksMat** [comment]
Version 0.2 of plugin now works with new SentinelHub WMS
