### ISSUE TITLE
Time controls not working

### ISSUE THREAD

**Issue by gmilcinski** [sinergise/qgis_sentinel_hub#4]
This is a known issue, which we have already noticed, but we do not know, how to fix it. If anyone has some idea, it would be welcome.

I am running the latest QGIS on OSX Sierra and time controls are not working at all. I see the calendar and I can click on dates, but these are not reflected in the time panel, neither on the map.

**Comment by AleksMat** [comment]
Time controls should work if you double click on dates. When you select new dates and update the viewing layer those changes should be reflected on map.

However I agree it would be more user-friendly if date selection would work on single click as well.

**Comment by gmilcinski** [comment]
Ah, I see, i did not know that. Cool, it works. Agree on the friendliness. Or at least some instructions somewhere... But as long as it works, I am closing this issue. Thanks.

**Comment by drorata** [comment]
@AleksMat can you please mention where I can find the date tools? I would like to be able to browse different dates for some given location.

**Comment by AleksMat** [comment]
Hi @drorata,

There is a "Time range" option where you can select dates from a calendar and thus specify the time interval of the data. Are you looking for something else?

![time-range](https://user-images.githubusercontent.com/9626750/64081325-a34d7500-ccff-11e9-86cd-ee17891c4c21.png)

**Comment by drorata** [comment]
I'm looking exactly for this but cannot find it... My version is 3.8.2-Zanzibar.
