### ISSUE TITLE
Compatibility with QGIS 3

### ISSUE THREAD

**Issue by GorgiAstro** [sinergise/qgis_sentinel_hub#5]
QGIS 3 was just released, and the Sentinel Hub plugin is not compatible with it.
The plugin is not listed in the plugin list, and if installing manually from ZIP file, the following message is displayed:
"This plugin is incompatible with this version of QGIS
Plugin designed for QGIS 2.0 - 2.99"

**Comment by mkadunc** [comment]
Fixed in https://github.com/sinergise/qgis_sentinel_hub/releases/tag/v1.0
