### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by JesusLopTem** [sinergise/qgis_sentinel_hub#9]
The 'SentinelHub' add-on could not be loaded due to an error calling its method classFactory() 

TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Volumes/Suevia/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SentinelHub/__init__.py", line 36, in classFactory
    return SentinelHub(iface)
  File "/Volumes/Suevia/Users/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SentinelHub/SentinelHub.py", line 165, in __init__
    locale = QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable

Python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] 
QGIS version: 3.0.3-Girona Girona, exported 

Ruta de Python:
/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Volumes/xxxxx/Users/xxxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Volumes/xxxxx/Users/xxxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Volumes/xxxxx/Users/xxxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Volumes/xxxxx/Users/xxxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Volumes/xxxxx/xxxxxxx/jesus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins

**Comment by AleksMat** [comment]
Hi Jesus,

thanks for letting us know about the error. It seems that in some rare cases (depending on OS and QGIS version) QGIS does not store local variables such as default system language. Because plugin did not consider this option an error was raised.

Now we fixed the problem and released a new plugin version `1.3.2`. It should be available in Official QGIS Repository in a few hours.

Thanks again. :)
